services:
  #web:
  #  build: .
  #  command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
  #  volumes:
  #    - .:/usr/src/app
  #    - bundle:/usr/local/bundle
  #  ports:
  #    - "3000:3000"
  #  env_file:
  #    - .env
  #  depends_on:
  #    - db
  #    - redis
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle:
