---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/version":
    get:
      summary: Get actual version
      responses:
        '200':
          description: With this request you could to get the last version of application
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
