development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= "redis://#{ENV.fetch("REDIS_URL")}/#{ENV.fetch("REDIS_PORT")}/#{ENV.fetch("REDIS_DB")}" %>
  channel_prefix: boilerplate_api_production
