development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  database: boilerplate_api_test
  #host: db
  host: localhost
  port: 5432

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  database: boilerplate_api_test
  #host: db
  host: localhost
  port: 5432
